Ernie feature setup
Ernie1234/shortit pull request #1
Opened 2024-05-27 22:43 UTC by Ernie1234

backend folders and files setup for backend

2024-05-28 10:03 UTC, Ernie1234 commented
backend setup and eslint

2024-06-03 21:47 UTC, greatertomi requested changes
Good initial setup. Please add [Airbnb rules](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb) don't forget to add [plugin with typescript](https://github.com/iamturns/eslint-config-airbnb-typescript) support. Also add [unicorn](https://github.com/sindresorhus/eslint-plugin-unicorn) and [sonarjs](https://github.com/SonarSource/eslint-plugin-sonarjs), I find them very helpful. Incase you are interested, you can find more awesome eslint plugins [here](https://github.com/dustinspecker/awesome-eslint).

Btw, if you want to add any rules apart from the ones I specify above, make sure you inform me.

2024-06-03 21:49 UTC, greatertomi commented
Also, your branch is not named properly. Read [this](https://medium.com/@abhay.pixolo/naming-conventions-for-git-branches-a-cheatsheet-8549feca2534). Btw, don't rename this branch, just note that for next time.

2024-06-05 20:18 UTC, Ernie1234 commented on src/index.ts
> +//For env File
Okay sir, noted sir!

2024-06-05 20:42 UTC, Ernie1234 commented on package.json
> +    "nodemon": "^3.1.1"
okay sir, done!

2024-06-07 12:29 UTC, closed without merging